#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 13 17:31:07 2020

@author: mls
"""

def checkBoundary(x,min,max):
    if not min<=x<=max:
        sys.exit("Input out of range (range is",min,"to",max)

def pisanoPeriod(m):
    prev,curr=1,1
    pisanolength=2
    while prev+curr>1:
        prev,curr=curr,(curr+prev)%m
        pisanolength+=1
    return pisanolength

def fibonacciLastTwo(n):
    previous, current=0,1
    if n<1: return previous,current
    for i in range(2,n+1):
        previous, current=current,(previous+current)%10
    return previous,current


n=int(input())
checkBoundary(n, 0, 100000000000000)
a,b=fibonacciLastTwo(n%pisanoPeriod(10))
sqrsum=((a+b)*b)%10
print(sqrsum)